apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dasks.piersharding.com
spec:
  group: piersharding.com
  version: v1
  scope: Namespaced
  names:
    plural: dasks
    singular: dask
    kind: Dask
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: dask-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: piersharding.com/v1
    resource: dasks
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://dask-controller.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-controller
  template:
    metadata:
      labels:
        app: dask-controller
    spec:
      containers:
      - name: controller
        image: piersharding/dask-controller:latest
        command: ["dask-controller"]
---
apiVersion: v1
kind: Service
metadata:
  name: dask-controller
  namespace: metacontroller
spec:
  selector:
    app: dask-controller
  ports:
  - port: 80
    targetPort: 8080
