---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pylibs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pylibs

---
apiVersion: piersharding.com/v1
kind: Dask
metadata:
  name: app-1
spec:
  # daemon: true
  jupyter: true
  replicas: 3
  image: piersharding/arl-dask:latest
  # image: piersharding/arl:ubuntu18.04
  # image: daskdev/dask:latest
  jupyterIngress: notebook.dask.local
  schedulerIngress: scheduler.dask.local
  imagePullPolicy: IfNotPresent
  env:
    - name: PYTHONPATH
      value: /pylibs:/arl
    - name: ARL
      value: /arl
    - name: ARL_DASK_SCHEDULER
      value: dask-scheduler-app1:8786
  volumes:
    - hostPath:
        path: /home/piers/git/private/algorithm-reference-library
        type: DirectoryOrCreate
      name: arl
    - name: pylibs
      persistentVolumeClaim:
        claimName: pylibs
  volumeMounts:
    - mountPath: /arl
      readOnly: false
      name: arl
    - mountPath: "/pylibs"
      name: pylibs

  # imagePullSecrets:
  #   - name: gitlab-registry
  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: mpi_job_role
  #           operator: In
  #           values:
  #             - app1-worker
  #       topologyKey: kubernetes.io/hostname
  # nodeSelector:
  #   kubernetes.io/os: linux
  # tolerations:
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
