apiVersion: piersharding.com/v1
kind: Dask
metadata:
  name: app-1
spec:
  message: Hello, World!
  daemon: true
  replicas: 2
  image: arl:ubuntu18.04
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: gitlab-registry
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: mpi_job_role
            operator: In
            values:
              - app1-worker
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
