{{ if .Values.controller.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dasks.piersharding.com
spec:
  group: piersharding.com
  version: v1
  scope: Namespaced
  names:
    plural: dasks
    singular: dask
    kind: Dask
  additionalPrinterColumns:
  - name: Replicas
    type: integer
    description: The number of Pods in the Dask
    JSONPath: .spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The Dask spec
          description: replicas should be specified
          properties:
            replicas:
              title: Total number of replicas
              description: Required replicas for the Dask cluster
              type: integer
              minimum: 1
            daemon:
              title: Daemon, strictly one per node
              description: Force Dask cluster to launch one per node
              type: boolean
          required:
          - replicas

{{ end }}
