
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-analytics-piersharding-com-v1-dask
  failurePolicy: Fail
  name: mdask.piersharding.com
  rules:
  - apiGroups:
    - analytics.piersharding.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dasks
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-analytics-piersharding-com-v1-daskjob
  failurePolicy: Fail
  name: mdaskjob.piersharding.com
  rules:
  - apiGroups:
    - analytics.piersharding.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daskjobs

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-analytics-piersharding-com-v1-dask
  failurePolicy: Fail
  name: vdask.piersharding.com
  rules:
  - apiGroups:
    - analytics.piersharding.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dasks
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-analytics-piersharding-com-v1-daskjob
  failurePolicy: Fail
  name: vdaskjob.piersharding.com
  rules:
  - apiGroups:
    - analytics.piersharding.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daskjobs
