apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vdask.piersharding.com
  clientConfig:
    caBundle: $(TLSCERT)
