# permissions to do viewer daskjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskjob-viewer-role
rules:
- apiGroups:
  - analytics.piersharding.com
  resources:
  - daskjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - analytics.piersharding.com
  resources:
  - daskjobs/status
  verbs:
  - get
