# permissions to do edit daskjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskjob-editor-role
rules:
- apiGroups:
  - analytics.piersharding.com
  resources:
  - daskjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - analytics.piersharding.com
  resources:
  - daskjobs/status
  verbs:
  - get
  - patch
  - update
