apiVersion: analytics.piersharding.com/v1
kind: DaskJob
metadata:
  name: simple1
spec:
  cluster: simple1
  report: true
  image: jupyter/scipy-notebook:latest
  imagePullPolicy: IfNotPresent
  script: https://raw.githubusercontent.com/piersharding/dask-operator/master/notebooks/array.ipynb